import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const { message, encounter } = await request.json();

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "GEMINI_API_KEY is not configured in the environment variables." },
        { status: 500 }
      );
    }

    const contextStr = encounter
      ? `Patient: ${encounter.patientName} (Age: ${encounter.age}, Gender: ${encounter.gender})
Chief Complaint: ${encounter.chiefComplaint}
HPI: ${encounter.historyOfPresentIllness || "None"}
PMH: ${encounter.pastMedicalHistory || "None"}
Meds: ${encounter.medications || "None"}
Allergies: ${encounter.allergies || "None"}
Vitals: ${encounter.vitals || "None"}
Exam: ${encounter.examFindings || "None"}
Labs: ${encounter.labs || "None"}
Assessment Notes: ${encounter.assessmentNotes || "None"}
SOAP Subjective: ${encounter.documentation?.soap?.subjective || "None"}
SOAP Objective: ${encounter.documentation?.soap?.objective || "None"}
SOAP Assessment: ${encounter.documentation?.soap?.assessment || "None"}
SOAP Plan: ${encounter.documentation?.soap?.plan || "None"}
Current Coding: ICD-10: ${JSON.stringify(encounter.coding?.icd10 || [])}, CPT: ${JSON.stringify(encounter.coding?.cpt || [])}`
      : "No encounter context is currently loaded.";

    const systemPrompt = `You are Operyx AI, an advanced, highly clinical AI assistant specialized in healthcare operations, clinical documentation, medical coding (ICD-10, CPT, HCPCS), clinical decision support (CDS), and billing compliance.

Here is the context of the current patient encounter:
---
${contextStr}
---

The user (a clinician or medical coder) asks: "${message}"

Please respond accurately, professionally, and in a clinician-friendly manner. Use markdown format.
Keep your response concise but detailed. Bold important terms using **double asterisks**.
Focus on clinical accuracy, medical coding compliance, or documentation specificity as relevant.`;

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [{ text: systemPrompt }],
            },
          ],
        }),
      }
    );

    if (!response.ok) {
      const errText = await response.text();
      return NextResponse.json(
        { error: `Gemini API error: ${response.statusText}. Details: ${errText}` },
        { status: response.status }
      );
    }

    const data = await response.json();
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text || "No response generated by Gemini.";

    return NextResponse.json({ content: text });
  } catch (error: any) {
    return NextResponse.json({ error: error.message || "An unexpected error occurred." }, { status: 500 });
  }
}
